/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Abner
 */
public class Mediana extends javax.swing.JFrame {

    /**
     * Creates new form Mediana
     */
    public Mediana() {
        initComponents();
        
        //edicion de ventana
        setIconImage(new ImageIcon(getClass().getResource("/iconos/principal.png")).getImage());
        this.setLocationRelativeTo(this);
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        //fin de la edicion de ventana
        
        formula();
        lb_resultado1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void formula(){
        ImageIcon fr;
       
        fr = new ImageIcon(getClass().getResource("/Iconos/mediana.png"));
        
        Icon frm = new ImageIcon(fr.getImage().getScaledInstance(lb_formula.getWidth(), lb_formula.getHeight(), Image.SCALE_SMOOTH)); 
        this.lb_formula.setIcon(frm);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_fondo = new javax.swing.JPanel();
        pn_encabezado = new javax.swing.JPanel();
        lb_encabezado = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();
        lb_formula = new javax.swing.JLabel();
        lb_donde = new javax.swing.JLabel();
        txt_n = new RSMaterialComponent.RSTextFieldIconUno();
        txt_a = new RSMaterialComponent.RSTextFieldIconUno();
        jPanel2 = new javax.swing.JPanel();
        lb_resultado1 = new javax.swing.JLabel();
        txt_Li = new RSMaterialComponent.RSTextFieldIconUno();
        txt_f = new RSMaterialComponent.RSTextFieldIconUno();
        txt_anterior = new RSMaterialComponent.RSTextFieldIconUno();
        bt_calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stax | Calculo de mediana");
        setUndecorated(true);

        lb_fondo.setBackground(new java.awt.Color(102, 102, 102));

        pn_encabezado.setBackground(new java.awt.Color(255, 102, 255));

        lb_encabezado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lb_encabezado.setForeground(new java.awt.Color(255, 255, 255));
        lb_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mas.png"))); // NOI18N
        lb_encabezado.setText("Calculo de la Mediana");
        lb_encabezado.setToolTipText("papa, entende, aqui no hay nada mas que un titulo");

        bt_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        bt_salir.setToolTipText("Bye, bye...");
        bt_salir.setBorderPainted(false);
        bt_salir.setContentAreaFilled(false);
        bt_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_encabezadoLayout = new javax.swing.GroupLayout(pn_encabezado);
        pn_encabezado.setLayout(pn_encabezadoLayout);
        pn_encabezadoLayout.setHorizontalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_encabezadoLayout.setVerticalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_encabezadoLayout.createSequentialGroup()
                        .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lb_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lb_donde.setBackground(new java.awt.Color(204, 204, 204));
        lb_donde.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lb_donde.setForeground(new java.awt.Color(255, 255, 255));
        lb_donde.setText("<html> <p><strong>Donde:</strong></p> <p><em>Li</em> = Limite inferior del intervalo,</p> <p><em>(F - 1)&nbsp;</em>=&nbsp;El dato anterior de <em>Fa</em> del intervalo seleccionado,</p> <p><em>N</em> = Es el total de datos del arreglo,</p> <p><em>f</em> = Frecuencia absoluta del intervalo,</p> <p><em>a</em> = amplitud del intervalo.</p>");

        txt_n.setForeground(new java.awt.Color(255, 0, 255));
        txt_n.setToolTipText("Cantidad de datos");
        txt_n.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_n.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_n.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_n.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_n.setPlaceholder("Cantidad de datos");
        txt_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nActionPerformed(evt);
            }
        });

        txt_a.setForeground(new java.awt.Color(255, 0, 255));
        txt_a.setToolTipText("Amplitud del intervalo");
        txt_a.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_a.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_a.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_a.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_a.setPlaceholder("Amplitud del intervalo");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lb_resultado1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lb_resultado1.setForeground(new java.awt.Color(255, 255, 255));
        lb_resultado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/respuesta1.png"))); // NOI18N
        lb_resultado1.setToolTipText("Este es el resultado. Vete ya de aqui.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_resultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lb_resultado1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        txt_Li.setForeground(new java.awt.Color(255, 0, 255));
        txt_Li.setToolTipText("Limite inferior del intervalo");
        txt_Li.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_Li.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_Li.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_Li.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_Li.setPlaceholder("Limite inferior del intervalo");

        txt_f.setForeground(new java.awt.Color(255, 0, 255));
        txt_f.setToolTipText("Frecuencia absoluta");
        txt_f.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_f.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_f.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_f.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_f.setPlaceholder("Frecuencia absoluta");

        txt_anterior.setForeground(new java.awt.Color(255, 0, 255));
        txt_anterior.setToolTipText("Frecuencia abs. anterior");
        txt_anterior.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_anterior.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_anterior.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_anterior.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_anterior.setPlaceholder("Frecuencia abs. anterior");

        bt_calcular.setBackground(new java.awt.Color(255, 102, 255));
        bt_calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calcular.png"))); // NOI18N
        bt_calcular.setToolTipText("Calcular la moda");
        bt_calcular.setBorderPainted(false);
        bt_calcular.setContentAreaFilled(false);
        bt_calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_calcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ok.png"))); // NOI18N
        bt_calcular.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ok.png"))); // NOI18N
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lb_fondoLayout = new javax.swing.GroupLayout(lb_fondo);
        lb_fondo.setLayout(lb_fondoLayout);
        lb_fondoLayout.setHorizontalGroup(
            lb_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lb_fondoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(lb_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_formula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_f, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_Li, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(lb_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_donde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        lb_fondoLayout.setVerticalGroup(
            lb_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_fondoLayout.createSequentialGroup()
                .addComponent(pn_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lb_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_donde, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_formula, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(lb_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lb_fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(lb_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lb_fondoLayout.createSequentialGroup()
                                .addComponent(txt_Li, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lb_fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    private void txt_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed

        float denominador;
        float numerador;
        float mediana;
        float div;
        float f = Float.parseFloat(txt_f.getText());
        float li = Float.parseFloat(txt_Li.getText());
        float fan = Float.parseFloat(txt_anterior.getText());
        float n = Float.parseFloat(txt_n.getText());
        float a = Float.parseFloat(txt_a.getText());

        numerador= ((n/2)-fan);
        denominador= f;
        div= (numerador/denominador);
        mediana= li+(div*a);

        String res = String.valueOf(mediana);
        this.lb_resultado1.setText(" La mediana es: "+res);
        this.lb_resultado1.setVisible(true);

    }//GEN-LAST:event_bt_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mediana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_salir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_donde;
    private javax.swing.JLabel lb_encabezado;
    private javax.swing.JPanel lb_fondo;
    private javax.swing.JLabel lb_formula;
    private javax.swing.JLabel lb_resultado1;
    private javax.swing.JPanel pn_encabezado;
    private RSMaterialComponent.RSTextFieldIconUno txt_Li;
    private RSMaterialComponent.RSTextFieldIconUno txt_a;
    private RSMaterialComponent.RSTextFieldIconUno txt_anterior;
    private RSMaterialComponent.RSTextFieldIconUno txt_f;
    private RSMaterialComponent.RSTextFieldIconUno txt_n;
    // End of variables declaration//GEN-END:variables
}
