/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CODEX.bayes;
import CODEX.condicional;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Abner
 */
public class Menu extends javax.swing.JFrame {

    
    
    public Menu() {
        initComponents();
        
        //edicion de ventana
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/principal.png")).getImage());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Iconos/icon.png")));
        this.setLocationRelativeTo(this);
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        //fin de la edicion de ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_fondo = new javax.swing.JPanel();
        pn_encabezado = new javax.swing.JPanel();
        lb_encabezado = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();
        bt_tablas = new javax.swing.JButton();
        bt_probabilidad = new javax.swing.JButton();
        bt_dispersion = new javax.swing.JButton();
        bt_nosotros = new javax.swing.JButton();
        lb_descripcion = new javax.swing.JLabel();
        lb_descripcion1 = new javax.swing.JLabel();
        lb_descripcion2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stax | Menu Principal");
        setUndecorated(true);

        pn_fondo.setBackground(new java.awt.Color(255, 102, 255));

        pn_encabezado.setBackground(new java.awt.Color(102, 102, 102));

        lb_encabezado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lb_encabezado.setForeground(new java.awt.Color(255, 255, 255));
        lb_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/principal.png"))); // NOI18N
        lb_encabezado.setText("Stax | Menu Principal");
        lb_encabezado.setToolTipText("papa, entende, aqui no hay nada mas que un titulo");

        bt_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        bt_salir.setToolTipText("Bye, bye...");
        bt_salir.setBorderPainted(false);
        bt_salir.setContentAreaFilled(false);
        bt_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_encabezadoLayout = new javax.swing.GroupLayout(pn_encabezado);
        pn_encabezado.setLayout(pn_encabezadoLayout);
        pn_encabezadoLayout.setHorizontalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_encabezadoLayout.setVerticalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_encabezadoLayout.createSequentialGroup()
                        .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lb_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_tablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tabla1.png"))); // NOI18N
        bt_tablas.setToolTipText("Calcula los valores de la tabla de frecuencias");
        bt_tablas.setBorderPainted(false);
        bt_tablas.setContentAreaFilled(false);
        bt_tablas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_tablas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lentes.png"))); // NOI18N
        bt_tablas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lentes.png"))); // NOI18N
        bt_tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tablasActionPerformed(evt);
            }
        });

        bt_probabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cartas.png"))); // NOI18N
        bt_probabilidad.setToolTipText("Calcula la probabilidad de eventos");
        bt_probabilidad.setBorderPainted(false);
        bt_probabilidad.setContentAreaFilled(false);
        bt_probabilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_probabilidad.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/feliz.png"))); // NOI18N
        bt_probabilidad.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/feliz.png"))); // NOI18N
        bt_probabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_probabilidadActionPerformed(evt);
            }
        });

        bt_dispersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dispersion.png"))); // NOI18N
        bt_dispersion.setToolTipText("Calcula los valores de dispersion de una serie de numeros");
        bt_dispersion.setBorderPainted(false);
        bt_dispersion.setContentAreaFilled(false);
        bt_dispersion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_dispersion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nerd.png"))); // NOI18N
        bt_dispersion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nerd.png"))); // NOI18N
        bt_dispersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dispersionActionPerformed(evt);
            }
        });

        bt_nosotros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nosotros.png"))); // NOI18N
        bt_nosotros.setToolTipText("Desarrolladores");
        bt_nosotros.setBorderPainted(false);
        bt_nosotros.setContentAreaFilled(false);
        bt_nosotros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_nosotros.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/jojo.png"))); // NOI18N
        bt_nosotros.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/jojo.png"))); // NOI18N
        bt_nosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nosotrosActionPerformed(evt);
            }
        });

        lb_descripcion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lb_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        lb_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_descripcion.setText("Tabla de frecuencias");
        lb_descripcion.setToolTipText("Descripcion");
        lb_descripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_descripcion1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lb_descripcion1.setForeground(new java.awt.Color(255, 255, 255));
        lb_descripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_descripcion1.setText("Calculo de Probabilidad");
        lb_descripcion1.setToolTipText("Descripcion");
        lb_descripcion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_descripcion2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lb_descripcion2.setForeground(new java.awt.Color(255, 255, 255));
        lb_descripcion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_descripcion2.setText("Medidas de dispersion");
        lb_descripcion2.setToolTipText("Descripcion");
        lb_descripcion2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pn_fondoLayout = new javax.swing.GroupLayout(pn_fondo);
        pn_fondo.setLayout(pn_fondoLayout);
        pn_fondoLayout.setHorizontalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_fondoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bt_tablas)
                        .addGap(145, 145, 145)
                        .addComponent(bt_probabilidad)
                        .addGap(146, 146, 146)
                        .addComponent(bt_dispersion))
                    .addGroup(pn_fondoLayout.createSequentialGroup()
                        .addComponent(lb_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lb_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lb_descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_nosotros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pn_fondoLayout.setVerticalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addComponent(pn_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_probabilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_dispersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(bt_nosotros, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_tablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tablasActionPerformed
    Tabla_Frec tb = new Tabla_Frec();
    tb.setVisible(true);
       
    }//GEN-LAST:event_bt_tablasActionPerformed

    private void bt_probabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_probabilidadActionPerformed
         
        
        
        String[] opcion ={
                               "Selecciona un calculo",
                               "Teorema de Bayes",
                               "Probabilidad Condicional",
                               "Ley de la Adicion",
                               "Ley de la Multiplicacion"
                         };
        ImageIcon icon = new ImageIcon("src/Iconos/mas.png");
        String pregunta = (String)JOptionPane.showInputDialog(null, "Selecciona el calculo a realizar: ", "Stax | Mas opciones",JOptionPane.QUESTION_MESSAGE,icon, opcion, opcion[0]);
       
        if(pregunta.equals("Teorema de Bayes")){
            bayes bayes = new bayes(); 
            bayes.setVisible(true);
            
        }
        if(pregunta.equals("Probabilidad Condicional")){
            condicional pc = new condicional();
            pc.setVisible(true);
            
        }
        
         if(pregunta.equals("Ley de la Multiplicacion")){
            calcular mu = new calcular();
            mu.setVisible(true);
            
        }
        
        if(pregunta.equals("Ley de la Adicion")){
            adicion ad = new adicion();
            ad.setVisible(true);
            
        }
        
        if(pregunta.equals("Selecciona un calculo")){
         }  else {
            //no hara nada, igual que lo que puedes hacer para que ella vuelva a tu lado.
        }
            
        
    }//GEN-LAST:event_bt_probabilidadActionPerformed

    private void bt_dispersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dispersionActionPerformed
       String[] opcion ={
                               "Selecciona un calculo",
                               "Desviacion Estandar",
                               "Covarianza",
                               "Varianza"
                               
                         };
        ImageIcon icon = new ImageIcon("src/Iconos/mas.png");
        String pregunta = (String)JOptionPane.showInputDialog(null, "Selecciona el calculo a realizar: ", "Stax | Mas opciones",JOptionPane.QUESTION_MESSAGE,icon, opcion, opcion[0]);
       
        if(pregunta.equals("Desviacion Estandar")){
            desviacion_estandar de = new desviacion_estandar(); 
            de.setVisible(true);
        }
        if(pregunta.equals("Covarianza")){
            Calc_2 de = new Calc_2(); 
            de.setVisible(true);
        }
        if(pregunta.equals("Varianza")){
            varianza v = new varianza(); 
            v.setVisible(true);
        }
        if(pregunta.equals("Selecciona un calculo")){
         }  else {
            //no hara nada, igual que lo que puedes hacer para que ella vuelva a tu lado.
         }
        
    }//GEN-LAST:event_bt_dispersionActionPerformed

    private void bt_nosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nosotrosActionPerformed
        Integrantes in = new Integrantes();
        in.setVisible(true);
    }//GEN-LAST:event_bt_nosotrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dispersion;
    private javax.swing.JButton bt_nosotros;
    private javax.swing.JButton bt_probabilidad;
    private javax.swing.JButton bt_salir;
    private javax.swing.JButton bt_tablas;
    private javax.swing.JLabel lb_descripcion;
    private javax.swing.JLabel lb_descripcion1;
    private javax.swing.JLabel lb_descripcion2;
    private javax.swing.JLabel lb_encabezado;
    private javax.swing.JPanel pn_encabezado;
    private javax.swing.JPanel pn_fondo;
    // End of variables declaration//GEN-END:variables
}
