/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Abner
 */
public class Moda extends javax.swing.JFrame {

    /**
     * Creates new form Moda
     */
    public Moda() {
        initComponents();
        //edicion de ventana
        setIconImage(new ImageIcon(getClass().getResource("/iconos/principal.png")).getImage());
        this.setLocationRelativeTo(this);
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        //fin de la edicion de ventana
        
        JOptionPane.showMessageDialog(null,"Recuerda que la -moda- es el numero que mas se repite entre el\n"
                                         + "conjunto de datos. Asi que ve a la columna -f- y busca el numero\n"
                                         + " que aparezca mas veces en la serie.","Stax dice: Antes de comenzar...",JOptionPane.INFORMATION_MESSAGE);
    
        formula();
        lb_resultado1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void formula(){
        ImageIcon fr;
       
        fr = new ImageIcon(getClass().getResource("/Iconos/Moda.jpg"));
        
        Icon frm = new ImageIcon(fr.getImage().getScaledInstance(lb_formula.getWidth(), lb_formula.getHeight(), Image.SCALE_SMOOTH)); 
        this.lb_formula.setIcon(frm);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_encabezado = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();
        lb_formula = new javax.swing.JLabel();
        lb_donde = new javax.swing.JLabel();
        txt_Li = new RSMaterialComponent.RSTextFieldIconUno();
        txt_f = new RSMaterialComponent.RSTextFieldIconUno();
        txt_anterior = new RSMaterialComponent.RSTextFieldIconUno();
        txt_siguiente = new RSMaterialComponent.RSTextFieldIconUno();
        txt_a = new RSMaterialComponent.RSTextFieldIconUno();
        jPanel2 = new javax.swing.JPanel();
        lb_resultado1 = new javax.swing.JLabel();
        bt_calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stax | Calculo de la moda");
        setUndecorated(true);

        pn_fondo.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));

        lb_encabezado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lb_encabezado.setForeground(new java.awt.Color(255, 255, 255));
        lb_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mas.png"))); // NOI18N
        lb_encabezado.setText("Calculo de la Moda");
        lb_encabezado.setToolTipText("papa, entende, aqui no hay nada mas que un titulo");

        bt_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        bt_salir.setToolTipText("Bye, bye...");
        bt_salir.setBorderPainted(false);
        bt_salir.setContentAreaFilled(false);
        bt_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lb_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lb_donde.setBackground(new java.awt.Color(204, 204, 204));
        lb_donde.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lb_donde.setForeground(new java.awt.Color(255, 255, 255));
        lb_donde.setText("<html>\n\n<p><strong>Donde:</strong></p>\n<p><em>Li</em> = Limite inferior del intervalo,</p>\n<p><em>(f - 1)&nbsp;</em>=&nbsp;El dato anterior de <em>f</em> del intervalo seleccionado,</p>\n<p><em>(f + 1)</em> = El dato siguiente de <em>f</em> del intervalo seleccionado,</p>\n<p><em>f</em> = Frecuencia absoluta del intervalo,</p>\n<p><em>a</em> = amplitud del intervalo.</p>");

        txt_Li.setForeground(new java.awt.Color(255, 0, 255));
        txt_Li.setToolTipText("Limite inferior del intervalo");
        txt_Li.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_Li.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_Li.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_Li.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_Li.setPlaceholder("Limite inferior del intervalo");

        txt_f.setForeground(new java.awt.Color(255, 0, 255));
        txt_f.setToolTipText("Frecuencia absoluta");
        txt_f.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_f.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_f.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_f.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_f.setPlaceholder("Frecuencia absoluta");

        txt_anterior.setForeground(new java.awt.Color(255, 0, 255));
        txt_anterior.setToolTipText("Frecuencia abs. anterior");
        txt_anterior.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_anterior.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_anterior.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_anterior.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_anterior.setPlaceholder("Frecuencia abs. anterior");

        txt_siguiente.setForeground(new java.awt.Color(255, 0, 255));
        txt_siguiente.setToolTipText("Frecuencia abs. siguiente");
        txt_siguiente.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_siguiente.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_siguiente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_siguiente.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_siguiente.setPlaceholder("Frecuencia abs. siguiente");
        txt_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_siguienteActionPerformed(evt);
            }
        });

        txt_a.setForeground(new java.awt.Color(255, 0, 255));
        txt_a.setToolTipText("Amplitud del intervalo");
        txt_a.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_a.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_a.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_a.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_a.setPlaceholder("Amplitud del intervalo");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lb_resultado1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lb_resultado1.setForeground(new java.awt.Color(255, 255, 255));
        lb_resultado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/respuesta1.png"))); // NOI18N
        lb_resultado1.setToolTipText("Este es el resultado. Vete ya de aqui.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_resultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lb_resultado1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        bt_calcular.setBackground(new java.awt.Color(255, 102, 255));
        bt_calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calcular.png"))); // NOI18N
        bt_calcular.setToolTipText("Calcular la moda");
        bt_calcular.setBorderPainted(false);
        bt_calcular.setContentAreaFilled(false);
        bt_calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_calcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ok.png"))); // NOI18N
        bt_calcular.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ok.png"))); // NOI18N
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_fondoLayout = new javax.swing.GroupLayout(pn_fondo);
        pn_fondo.setLayout(pn_fondoLayout);
        pn_fondoLayout.setHorizontalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_a, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(txt_siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_f, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_Li, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_formula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(pn_fondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_donde, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pn_fondoLayout.setVerticalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_formula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_donde, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_fondoLayout.createSequentialGroup()
                        .addComponent(txt_Li, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(bt_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        this.dispose();

    }//GEN-LAST:event_bt_salirActionPerformed

    private void txt_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_siguienteActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        
        float denominador;
        float numerador;
        float moda;
        float div;
        float f = Float.parseFloat(txt_f.getText());
        float li = Float.parseFloat(txt_Li.getText());
        float fan = Float.parseFloat(txt_anterior.getText());
        float fsig = Float.parseFloat(txt_siguiente.getText());
        float a = Float.parseFloat(txt_a.getText());
        
        numerador= f - fan;
        denominador= (f-fan)+(f-fsig);
        div= (numerador/denominador);
        moda= li+(div*a);
        
        String res = String.valueOf(moda);
        this.lb_resultado1.setText(" La moda es: "+res);
        this.lb_resultado1.setVisible(true);
        
    }//GEN-LAST:event_bt_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_donde;
    private javax.swing.JLabel lb_encabezado;
    private javax.swing.JLabel lb_formula;
    private javax.swing.JLabel lb_resultado1;
    private javax.swing.JPanel pn_fondo;
    private RSMaterialComponent.RSTextFieldIconUno txt_Li;
    private RSMaterialComponent.RSTextFieldIconUno txt_a;
    private RSMaterialComponent.RSTextFieldIconUno txt_anterior;
    private RSMaterialComponent.RSTextFieldIconUno txt_f;
    private RSMaterialComponent.RSTextFieldIconUno txt_siguiente;
    // End of variables declaration//GEN-END:variables
}
