
package UI;

import CODEX.Clases;
import CODEX.Frecuencias;
import CODEX.dlgGraf;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abner
 */
public class Tabla_Frec extends javax.swing.JFrame {

    //private static final long serialVersionUID =1L;
    private Frecuencias frec;
   
    
    public Tabla_Frec() {
        initComponents();
        
        //Creamos objeto para usarlo a lo largo de la clase
        frec = new Frecuencias();
        
        
        //edicion de ventana
        setIconImage(new ImageIcon(getClass().getResource("/iconos/principal.png")).getImage());
        this.setLocationRelativeTo(this);
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        //fin de la edicion de ventana
        
        //algunas configuraciones
        txt_ingresar.setColumns(25);
        atxt_previa.setColumns(30);
        atxt_previa.setEditable(false);
        atxt_previa.setLineWrap(true);
        atxt_previa.setRows(10);
        bt_calcular.setEnabled(false);
        bt_borrar.setEnabled(false);
        bt_limpiar.setEnabled(false);
        bt_mas.setEnabled(false);
        bt_graficos.setEnabled(false);
       
        tb_tabla.setModel(new javax.swing.table.DefaultTableModel(new Object [][]{
            {null,null,null,null,null,null,null,null}}, 
                new String[]{
                "[ X - X >", "f", "Fa", "fi", "Fi","f%","F%","x·f"}));
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_encabezado = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();
        txt_ingresar = new RSMaterialComponent.RSTextFieldIconUno();
        pn_menu = new javax.swing.JPanel();
        bt_borrar = new rojerusan.RSButtonIconI();
        bt_agregar = new rojerusan.RSButtonIconI();
        bt_calcular = new rojerusan.RSButtonIconI();
        bt_limpiar = new rojerusan.RSButtonIconI();
        bt_mas = new rojerusan.RSButtonIconI();
        bt_graficos = new rojerusan.RSButtonIconI();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxt_previa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stax | Calculos Estadisticos");
        setUndecorated(true);

        pn_fondo.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));

        lb_encabezado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lb_encabezado.setForeground(new java.awt.Color(153, 0, 153));
        lb_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/principal.png"))); // NOI18N
        lb_encabezado.setText("Stax | Tabla de Frecuencias");
        lb_encabezado.setToolTipText("Este es un titulo");

        bt_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        bt_salir.setToolTipText("Bye, bye...");
        bt_salir.setBorderPainted(false);
        bt_salir.setContentAreaFilled(false);
        bt_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llorar.png"))); // NOI18N
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lb_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txt_ingresar.setForeground(new java.awt.Color(255, 0, 255));
        txt_ingresar.setText("63,43,64,59,50,82,51,72,60,64,36,70,52,67,76,49,57,51,57,44,56,62,62,67,73,64,43,60,61,56,59,68,71,67,62,35,62,61,51,63,78,26,55,81,60");
        txt_ingresar.setToolTipText("Ingresa el conjunto de datos a calcular");
        txt_ingresar.setBorderColor(new java.awt.Color(255, 51, 255));
        txt_ingresar.setColorIcon(new java.awt.Color(255, 51, 255));
        txt_ingresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_ingresar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.QUEUE);
        txt_ingresar.setPlaceholder("Ingresa los datos a calcular");

        pn_menu.setBackground(new java.awt.Color(255, 204, 255));
        pn_menu.setLayout(null);

        bt_borrar.setBackground(new java.awt.Color(255, 204, 255));
        bt_borrar.setBorder(null);
        bt_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/borrar.png"))); // NOI18N
        bt_borrar.setToolTipText("Borrar ingreso");
        bt_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarActionPerformed(evt);
            }
        });
        pn_menu.add(bt_borrar);
        bt_borrar.setBounds(10, 0, 60, 40);

        bt_agregar.setBackground(new java.awt.Color(255, 204, 255));
        bt_agregar.setBorder(null);
        bt_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        bt_agregar.setToolTipText("Previsualizar Datos");
        bt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarActionPerformed(evt);
            }
        });
        pn_menu.add(bt_agregar);
        bt_agregar.setBounds(70, 0, 60, 40);

        bt_calcular.setBackground(new java.awt.Color(255, 204, 255));
        bt_calcular.setBorder(null);
        bt_calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calcular.png"))); // NOI18N
        bt_calcular.setToolTipText("Calcular valores de la tabla");
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });
        pn_menu.add(bt_calcular);
        bt_calcular.setBounds(130, 0, 60, 40);

        bt_limpiar.setBackground(new java.awt.Color(255, 204, 255));
        bt_limpiar.setBorder(null);
        bt_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/limpiar todo.png"))); // NOI18N
        bt_limpiar.setToolTipText("Limpiar todo");
        bt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarActionPerformed(evt);
            }
        });
        pn_menu.add(bt_limpiar);
        bt_limpiar.setBounds(310, 0, 60, 40);

        bt_mas.setBackground(new java.awt.Color(255, 204, 255));
        bt_mas.setBorder(null);
        bt_mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mas.png"))); // NOI18N
        bt_mas.setToolTipText("mas opciones...");
        bt_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_masActionPerformed(evt);
            }
        });
        pn_menu.add(bt_mas);
        bt_mas.setBounds(190, 0, 60, 40);

        bt_graficos.setBackground(new java.awt.Color(255, 204, 255));
        bt_graficos.setBorder(null);
        bt_graficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Grafica.png"))); // NOI18N
        bt_graficos.setToolTipText("Ver Grafica");
        bt_graficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_graficosActionPerformed(evt);
            }
        });
        pn_menu.add(bt_graficos);
        bt_graficos.setBounds(250, 0, 60, 40);

        atxt_previa.setColumns(20);
        atxt_previa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        atxt_previa.setForeground(new java.awt.Color(255, 51, 255));
        atxt_previa.setRows(5);
        atxt_previa.setToolTipText("Previasualizacion de datos");
        jScrollPane1.setViewportView(atxt_previa);

        tb_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_tabla);

        javax.swing.GroupLayout pn_fondoLayout = new javax.swing.GroupLayout(pn_fondo);
        pn_fondo.setLayout(pn_fondoLayout);
        pn_fondoLayout.setHorizontalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_fondoLayout.createSequentialGroup()
                        .addComponent(txt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
        );
        pn_fondoLayout.setVerticalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarActionPerformed
        this.txt_ingresar.setText("");
    }//GEN-LAST:event_bt_borrarActionPerformed

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
        
        String [] str = txt_ingresar.getText().trim().split(","); //obtendra el texto y cortara cada vez que encuentre una coma
        float[]datos = new float[str.length]; //se le asigna el largo de string de ingreso
        
        for(int i=0; i < datos.length; i++){        //este men recorrear todo los datos, convertira los string a decimales y los guardara en el txt area.
            datos[i] = Float.parseFloat(str[i]);
            atxt_previa.append(str[i] +" ");
        }
        frec.setValor(datos); //le pasamos datos a el parametro de la funcion setValor de la clase Frecuencias
        txt_ingresar.setText(" ");  //dejara en blanco la casilla
        bt_calcular.setEnabled(true); //habilita el boton calculo
        bt_borrar.setEnabled(true);
        bt_limpiar.setEnabled(true);
        bt_mas.setEnabled(true);
        
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        
        Clases[] clases = frec.getClases(); //creamos un objeto nuevo de la clase "clases" que contiene algunos claculos
        Clases cl = new Clases();
        
        DefaultTableModel modelo = (DefaultTableModel) tb_tabla.getModel();  //creamos un objeto tipo tabla y lo asignamos a tb_tabla
            
            int n = frec.getK();
            int[] abs = frec.getFrecAbs();
            int[] absAc = frec.getFrecAbsAc();
            float[] rel = frec.getFrecRel();
            float[] relAc = frec.getFrecRelAc();        //a cada "atributo" le asignamos el valor que retornan las funciones correspondientes
            
            
            atxt_previa.append("\n N = " + frec.getValor().length);
            atxt_previa.append("\n R = " + frec.getRango());
            atxt_previa.append("\n K = " + frec.getK());
            atxt_previa.append("\n A = " + frec.getA());    //mandamos cada dato al final del texto (uno tras otro por medio del append)
            
            borrarFilas();
        
                for(int i=0; i < n; i++){
                    
                    /* index [0] CLASES */ String str = "[" + Math.round(clases[i].getLimInf()) + "," + Math.round(clases[i].getLimSup()) + " >";
                    /* index [1] f      */ modelo.addRow(new String[]{str, abs[i] + "", absAc[i] + ""}); //como son enteros se configuran e insertan de una
                    /* index [2] fr     */ modelo.setValueAt(redondear(rel[i], 4), i, 3);
                    /* index [3] Fr     */ modelo.setValueAt(redondear(relAc[i], 4), i, 4);
                    /* index [4] f%     */ modelo.setValueAt(redondear(rel[i], 4)*100, i, 5);
                    /* index [5] f%     */ modelo.setValueAt(redondear(relAc[i], 4)*100, i, 6);
                                           String str1 = ""+ ((Math.round(clases[i].getLimSup()) + Math.round(clases[i].getLimInf()))/2)*(abs[i]);
                    /* index [6] x.f    */ modelo.setValueAt(str1,i,7);
               
                }
                
                //obteniendo la suma de xf y el calculo de la media (x) donde n = getValor
                 int fila=0;
                 int Suma=0;
                 float X=1;
                        for(int j=0; j<tb_tabla.getRowCount(); j++){
                           
                            fila = Integer.parseInt(String.valueOf(tb_tabla.getValueAt(j, 7))); //(x,y) (filas,columnas)
                            Suma+=fila;
                            X= (float)(Suma/frec.getValor().length); 
                        }
                atxt_previa.append("\n X = "+X+" (Media)");
                // fin de la media
                
                //calcular la mediana 
                //paso uno validar condiciones
                
                int N;
                N= (frec.getValor().length);
                
                if(N %2== 0){
                    int par = (frec.getValor().length)/2;
                    atxt_previa.append("\n\nObserva que n="+N+" es un numero par, asi que se utilizo la formula n/2."
                            +"\nDonde "+par+" es un valor en la coumna (Fa), de no existir, busca el entero mayor proximo. ");
                }
                
                if(N %2 !=0){
                    int impar = ((frec.getValor().length)+1)/2;
                    atxt_previa.append("\n\nObserva que n="+N+" es un numero impar, asi que se utilizo la formula (n+1)/2."
                            +"\nDonde "+impar+" es un valor en la coumna (Fa), de no existir, busca el entero mayor proximo. ");
                }
                
                
                
                bt_graficos.setEnabled(true);
    }//GEN-LAST:event_bt_calcularActionPerformed

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tb_tabla.getModel();
        int pregunta = JOptionPane.showConfirmDialog(pn_fondo, "¿Estas seguro de eliminar el contenido de la tabla, \n aun estas a tiempo de cambiar tu vida Bro?",
                      "Stax pregunta: ¿Realmente deseas hacer esto?",JOptionPane.OK_CANCEL_OPTION,QUESTION_MESSAGE);
        
         if(pregunta == JOptionPane.OK_OPTION){
             //Limpia textArea
             atxt_previa.setText("");  
        
            //limpia tabla 
                int fila1 = tb_tabla.getRowCount();
                for(int i = fila1-1; i>=0; i--){
                modelo.removeRow(i);
                }
                
             JOptionPane.showMessageDialog(null,"¡Uy quieto! Que rebelde","Me asombras :o",JOptionPane.WARNING_MESSAGE);
         }
         
         if(pregunta ==JOptionPane.CANCEL_OPTION){
            //no hara nada, igual que lo que puedes hacer para que ella vuelva a tu lado.
         }
        
        
        
    }//GEN-LAST:event_bt_limpiarActionPerformed

    private void bt_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_masActionPerformed
       
        
        
        
        String[] opcion ={
                               "Selecciona un calculo",
                               "Mediana",
                               "Moda"
                         };
        ImageIcon icon = new ImageIcon("src/Iconos/mas.png");
        String pregunta = (String)JOptionPane.showInputDialog(null, "Selecciona el calculo a realizar: ", "Stax | Mas opciones",JOptionPane.QUESTION_MESSAGE,icon, opcion, opcion[0]);
       
        if(pregunta.equals("Mediana")){
            Mediana me = new Mediana();
            me.setVisible(true);
            
        }
        if(pregunta.equals("Moda")){
            Moda mo = new Moda();
            mo.setVisible(true);
            
        }
        
        if(pregunta.equals("Selecciona un calculo")){
         } else {
            //no hara nada, igual que lo que puedes hacer para que ella vuelva a tu lado.
        }
    }//GEN-LAST:event_bt_masActionPerformed

    private void bt_graficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_graficosActionPerformed
        dlgGraf graf=new dlgGraf(frec, this, true);
        graf.setLocationRelativeTo(this);
        graf.setVisible(true);
    }//GEN-LAST:event_bt_graficosActionPerformed

    private void borrarFilas() {
        DefaultTableModel modelo = (DefaultTableModel) tb_tabla.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(0);
        }
    }
    
    private float redondear(float d, int i) {
        float valor = 0;
        int factor=10*(i+1);
        valor = d;
        valor = valor * factor;
        valor = java.lang.Math.round(valor);
        valor = valor / factor;

        return valor;
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_Frec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_Frec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_Frec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_Frec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_Frec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxt_previa;
    private rojerusan.RSButtonIconI bt_agregar;
    private rojerusan.RSButtonIconI bt_borrar;
    private rojerusan.RSButtonIconI bt_calcular;
    private rojerusan.RSButtonIconI bt_graficos;
    private rojerusan.RSButtonIconI bt_limpiar;
    private rojerusan.RSButtonIconI bt_mas;
    private javax.swing.JButton bt_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_encabezado;
    private javax.swing.JPanel pn_fondo;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JTable tb_tabla;
    private RSMaterialComponent.RSTextFieldIconUno txt_ingresar;
    // End of variables declaration//GEN-END:variables
}
